### PING
GET http://localhost:3000/
User-Agent: {{user_agent}}

###

### SIGNUP - Create a new user
POST http://localhost:4000/api/auth/register
Content-Type: application/json
User-Agent: {{user_agent}}

{
  "first_name": "Nabil",
  "last_name": "AZOUZ",
  "email": "nabilos.fb@gmail.com",
  "username": "xezzuz",
  "password": "15987532468Nn*"
}

###


### SIGNUP - Create a new user
POST http://localhost:4000/api/auth/register
Content-Type: application/json
User-Agent: {{user_agent}}

{
  "first_name": "Achraf",
  "last_name": "AZOUZ",
  "email": "zilwa@gmail.com",
  "username": "xezzuzjr"
}

###

### LOGIN - Get a JWT ACCESS + REFRESH token
POST http://localhost:4000/api/auth/login
Content-Type: application/json
User-Agent: {{user_agent}}

{
  "username": "xezzuz",
  "password": "15987532468Nn*"
}

###

### COPY the token from the previous response and paste it below

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUwOTU2NTA0LCJleHAiOjE3NTA5NTc0MDR9.vkqQOlcMv0K4XpjqHJqjCOzI_C4tUJ5koJL_0kqLK9c
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInNlc3Npb25faWQiOiJhMmI4NzEyNTcxYWIwMTJkY2MzNjZkODc3MzVhYjA0YzE0NWJjMzc5ZWVmNjgxMGQ2NmQ2ODYwYzQ5YzNiM2VmIiwidmVyc2lvbiI6MywiaWF0IjoxNzQ4NzIxMTgyLCJleHAiOjE3NDkzMjU5ODJ9.PoCLTvlrftj-qhLsERmaAQir8AbOkJK02CxnnDIzW0g
@user_agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
@user_agent_device_change = Mozilla/5.0 (X11; Ubuntu 20.10; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
@user_agent_browser_change = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Brave/1.76.82 Safari/537.36

###

### Refresh Access Token
GET http://localhost:4000/protected
Authorization: Bearer {{access_token}}
# User-Agent: {{user_agent}}

###

### LOGOUT
POST http://localhost:3000/api/auth/logout
Authorization: Bearer {{refresh_token}}
User-Agent: {{user_agent}}

###

### GET Todos (should be empty at first)
GET http://localhost:3000/api/todos
Authorization: Bearer {{token}}

###

### CREATE a new Todo
POST http://localhost:3000/api/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "3zoz",
  "description": false
}

###

### GET Todos again (should include the new one)
GET http://localhost:3000/api/todos
Authorization: Bearer {{token}}

###

### UPDATE the Todo (replace ID with the real ID)
PATCH http://localhost:3000/api/todos/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "3zoz_updated",
  "completed": false
}

###

### DELETE the Todo
DELETE http://localhost:3000/api/todos/1
Authorization: Bearer {{token}}

###

### GET Todos again (should be empty again)
GET http://localhost:3000/api/todos/1
Authorization: Bearer {{token}}